/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.cpustressor2;

import java.awt.Color;
import java.awt.Component;
import java.awt.Dimension;
import java.awt.FlowLayout;
import java.awt.GridLayout;
import java.util.ArrayList;
import java.util.List;
import javax.swing.BoxLayout;
import javax.swing.ImageIcon;
import javax.swing.JCheckBox;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author pedro
 */
public class MainScreen extends javax.swing.JFrame {

    /**
     * Creates new form MainScreen
     */
   private JLabel gifLabel;

public MainScreen() {
    initComponents();

    getContentPane().setBackground(Color.RED);

    ImageIcon gifIcon = new ImageIcon(getClass().getResource("/gifs/flame.gif"));
    gifLabel = new JLabel(gifIcon);
    gifLabel.setBounds(100, 100, gifIcon.getIconWidth(), gifIcon.getIconHeight());
    gifLabel.setVisible(false);
    getContentPane().setLayout(null);
    getContentPane().add(gifLabel);

    mainPanel.setLayout(new BoxLayout(mainPanel, BoxLayout.Y_AXIS));
    rbPrioridadeMed.setSelected(true);
    
    labelDuracao.setText("Duração (em segundos):");
   

    adicionarCheckboxesDinamicamente();
}


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        mainPanel = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        labelDuracao = new javax.swing.JLabel();
        textDuracao = new javax.swing.JTextField();
        labelPrioridade = new javax.swing.JLabel();
        rbPrioridadeMin = new javax.swing.JRadioButton();
        rbPrioridadeMed = new javax.swing.JRadioButton();
        rbPrioridadeMaz = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 51, 51));
        setForeground(java.awt.Color.red);

        mainPanel.setBackground(new java.awt.Color(255, 51, 51));
        mainPanel.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        mainPanel.setForeground(new java.awt.Color(255, 51, 51));

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 159, Short.MAX_VALUE)
        );

        jButton1.setText("Burn");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        labelDuracao.setText("jLabel1");

        textDuracao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textDuracaoActionPerformed(evt);
            }
        });

        labelPrioridade.setText("Prioridade");

        buttonGroup1.add(rbPrioridadeMin);
        rbPrioridadeMin.setText("Mínima");

        buttonGroup1.add(rbPrioridadeMed);
        rbPrioridadeMed.setText("Normal");
        rbPrioridadeMed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbPrioridadeMedActionPerformed(evt);
            }
        });

        buttonGroup1.add(rbPrioridadeMaz);
        rbPrioridadeMaz.setText("Máxima");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(71, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(labelDuracao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(textDuracao, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(labelPrioridade, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 94, Short.MAX_VALUE)
                                .addComponent(rbPrioridadeMin)
                                .addGap(18, 18, 18)
                                .addComponent(rbPrioridadeMed)
                                .addGap(18, 18, 18)
                                .addComponent(rbPrioridadeMaz)))
                        .addGap(32, 32, 32))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(219, 219, 219))))
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(28, Short.MAX_VALUE)
                .addComponent(mainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelDuracao)
                    .addComponent(textDuracao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelPrioridade)
                    .addComponent(rbPrioridadeMin)
                    .addComponent(rbPrioridadeMed)
                    .addComponent(rbPrioridadeMaz))
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addGap(20, 20, 20))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
 
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        gifLabel.setVisible(true);
        CpuStress cpu = new CpuStress();

        System.out.println("Número de núcleos desse PC é de " + cpu.getNumbersOfGpu());
        List<Integer> selecionados = new ArrayList<>();

    for (JCheckBox checkbox : checkboxes) {
        if (checkbox.isSelected()) {
            selecionados.add(Integer.valueOf(checkbox.getActionCommand()));
        }
    }

    if (selecionados.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Selecione pelo menos um núcleo.");
        gifLabel.setVisible(false);
        return;
    }
    
    if (textDuracao.getText().isEmpty()){
        JOptionPane.showMessageDialog(this, "Selecione a duração.");
        gifLabel.setVisible(false);
        return;
    }
    
    int priority = 5;
    if(rbPrioridadeMaz.isSelected()){
         priority = 99;
    }else if(rbPrioridadeMin.isSelected()){
       priority = 1;
    }
   
        try {
            int temp = Integer.parseInt(textDuracao.getText());
            int[] cores = selecionados.stream().mapToInt(i -> i).toArray();
            cpu.stressCores(cores, temp, priority);
            System.out.println("Terminou");
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Duração formatada incorretamente");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void textDuracaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textDuracaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textDuracaoActionPerformed

    private void rbPrioridadeMedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbPrioridadeMedActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbPrioridadeMedActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainScreen().setVisible(true);
            }
        });
    }
private java.util.List<JCheckBox> checkboxes = new ArrayList<>();

private void adicionarCheckboxesDinamicamente() {
    int numNucleos = Runtime.getRuntime().availableProcessors();

    // Painel interno com GridLayout: 4 linhas por coluna, com 5px de espaçamento
    JPanel gridPanel = new JPanel(new GridLayout(4, 3, 95, 10));

    for (int i = 0; i < numNucleos; i++) {
        JCheckBox checkbox = new JCheckBox("Núcleo " + i);
        checkbox.setActionCommand(String.valueOf(i));
        checkboxes.add(checkbox);
        gridPanel.add(checkbox);
    }

    // Define o layout externo como FlowLayout para evitar esticar os checkboxes
    mainPanel.setLayout(new FlowLayout(FlowLayout.LEFT)); // ou CENTER
    mainPanel.removeAll(); // limpa checkboxes antigos, se houver
    mainPanel.add(gridPanel);

    mainPanel.revalidate();
    mainPanel.repaint();
}


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel labelDuracao;
    private javax.swing.JLabel labelPrioridade;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JRadioButton rbPrioridadeMaz;
    private javax.swing.JRadioButton rbPrioridadeMed;
    private javax.swing.JRadioButton rbPrioridadeMin;
    private javax.swing.JTextField textDuracao;
    // End of variables declaration//GEN-END:variables
}
